from __future__ import annotations

from .specs import (
    ExportTarget,
    FigureJob,
    GeometryEvolutionSpec,
    GeometryResponseMapsSpec,
    HeatmapSpec,
    HeatmapPairSpec,
    ImageComparisonGridSpec,
    LineGridSpec,
    LinePlusHeatmapSpec,
    PairedBoxplotSpec,
    PanelSpec,
    CompletionVisualGridSpec,
    SpatialCaseGridSpec,
    SortedGainGridSpec,
    SpectraPanelSpec,
)


FIGURE_REGISTRY = [
    FigureJob(
        spec=PairedBoxplotSpec(
            figure_id="linear_consistency_paired_gap",
            family="paired_boxplot",
            title="Linear consistency paired RMSE gap",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="linear_consistency_paired_gap",
                role="single_column",
            ),
            latex_path="./inputs/figures/main/linear_consistency_paired_gap.pdf",
            latex_width="\\linewidth",
            height=2.2,
            recommended_pairing="Standalone main-text figure.",
        ),
        aggregate_key="linear_paired_gap",
    ),
    FigureJob(
        spec=LineGridSpec(
            figure_id="nonlinear_pmax_grid",
            family="line_grid",
            title="Controlled nonlinear residuals: performance vs P",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="nonlinear_pmax_grid",
                role="double_column",
            ),
            latex_path="./inputs/figures/main/nonlinear_pmax_grid.pdf",
            latex_width="\\textwidth",
            height=4.8,
            shared_legend=True,
            panels=(
                PanelSpec("poly2", "poly2", r"$P$", "NMSE (dB)", (1, 2, 3, 4, 5, 6)),
                PanelSpec("poly3", "poly3", r"$P$", "NMSE (dB)", (1, 2, 3, 4, 5, 6)),
                PanelSpec("sin", "sin", r"$P$", "NMSE (dB)", (1, 2, 3, 4, 5, 6)),
                PanelSpec("tanh", "tanh", r"$P$", "NMSE (dB)", (1, 2, 3, 4, 5, 6)),
            ),
            method_order=("Tucker", "NTD-PL"),
            recommended_pairing="Keep alone or pair with the alpha sweep in a consecutive float block.",
        ),
        aggregate_key="nonlinear_pmax_grid",
    ),
    FigureJob(
        spec=LineGridSpec(
            figure_id="nonlinear_alpha_grid",
            family="line_grid",
            title="Controlled nonlinear residuals: performance vs alpha",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="nonlinear_alpha_grid",
                role="double_column",
            ),
            latex_path="./inputs/figures/main/nonlinear_alpha_grid.pdf",
            latex_width="\\textwidth",
            height=4.8,
            shared_legend=True,
            panels=(
                PanelSpec("poly2", "poly2", r"$\alpha$", "NMSE (dB)", (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40)),
                PanelSpec("poly3", "poly3", r"$\alpha$", "NMSE (dB)", (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40)),
                PanelSpec("sin", "sin", r"$\alpha$", "NMSE (dB)", (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40)),
                PanelSpec("tanh", "tanh", r"$\alpha$", "NMSE (dB)", (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40)),
            ),
            method_order=("Tucker", "CP", "TT", "TR", "NTD-PL"),
            recommended_pairing="Keep alone or pair with the P sweep in a consecutive float block.",
        ),
        aggregate_key="nonlinear_alpha_grid",
    ),
    FigureJob(
        spec=LineGridSpec(
            figure_id="nonlinear_step_grid",
            family="step_line_grid",
            title="Optimization trajectories under fixed nonlinear strength",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="nonlinear_step_grid",
                role="double_column",
            ),
            latex_path="./inputs/figures/main/nonlinear_step_grid.pdf",
            latex_width="\\textwidth",
            height=4.8,
            shared_legend=False,
            panels=(
                PanelSpec("poly2", "poly2", "Iteration", "RMSE"),
                PanelSpec("poly3", "poly3", "Iteration", "RMSE"),
                PanelSpec("sin", "sin", "Iteration", "RMSE"),
                PanelSpec("tanh", "tanh", "Iteration", "RMSE"),
            ),
            method_order=("NTD-PL",),
            recommended_pairing="Standalone main-text trend figure.",
        ),
        aggregate_key="nonlinear_step_grid",
    ),
    FigureJob(
        spec=SortedGainGridSpec(
            figure_id="cave_reconstruction_scene_gain",
            family="sorted_gain_grid",
            title="Scene-wise gains on CAVE full-observation reconstruction",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="cave_reconstruction_scene_gain",
                role="appendix_wide",
            ),
            latex_path="./inputs/figures/appendix/cave_reconstruction_scene_gain.pdf",
            latex_width="\\textwidth",
            height=3.3,
            panels=(PanelSpec("cave_reconstruction", "Scene-wise RMSE gain", "Scene index (sorted)", r"$\Delta$RMSE"),),
            recommended_pairing="Appendix-facing scene-level consistency summary.",
            appendix_only=True,
        ),
        aggregate_key="cave_representation_scene_improvement",
    ),
    FigureJob(
        spec=ImageComparisonGridSpec(
            figure_id="cave_reconstruction_visual_grid",
            family="image_comparison_grid",
            title="Representative pseudo-RGB reconstruction comparison",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="cave_reconstruction_visual_grid",
                role="appendix_wide",
            ),
            latex_path="./inputs/figures/appendix/cave_reconstruction_visual_grid.pdf",
            latex_width="\\textwidth",
            height=5.35,
            scene_order=(14, 8, 2),
            panel_order=("original", "tucker", "ntdpl", "tucker_error", "ntdpl_error", "error_reduction"),
            diff_panel="error_reduction",
            colorbar_label="Tucker - NTD-PL (>0 better)",
            recommended_pairing="Appendix-facing visual evidence for reconstruction.",
            appendix_only=True,
        ),
        aggregate_key="cave_representation_image_panels",
    ),
    FigureJob(
        spec=SpectraPanelSpec(
            figure_id="cave_reconstruction_spectra",
            family="spectra_panel",
            title="Representative spectral curves on CAVE",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="cave_reconstruction_spectra",
                role="appendix_wide",
            ),
            latex_path="./inputs/figures/appendix/cave_reconstruction_spectra.pdf",
            latex_width="\\textwidth",
            height=5.65,
            scene_order=(14, 8, 2),
            shared_legend=True,
            recommended_pairing="Appendix-facing spectral support figure.",
            appendix_only=True,
        ),
        aggregate_key="cave_representation_spectra",
    ),
    FigureJob(
        spec=HeatmapPairSpec(
            figure_id="cave_completion_scene_gain",
            family="heatmap_pair",
            title="Scene x rate consistency of missing-only gains",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="cave_completion_scene_gain",
                role="appendix_wide",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/appendix/cave_completion_scene_gain.png",
            latex_width="\\textwidth",
            height=5.35,
            x_label=r"Missing rate $\rho$",
            y_label="Scene",
            left_value_col="delta_rmse_missing",
            right_value_col="delta_sam_missing",
            left_title=r"$\Delta$RMSE*",
            right_title=r"$\Delta$SAM*",
            left_value_label=r"$\Delta$RMSE*",
            right_value_label=r"$\Delta$SAM*",
            cmap="RdBu_r",
            center_zero=True,
            x_col="missing_rate_label",
            y_col="scene_label",
            recommended_pairing="Appendix-facing scene x rate consistency map.",
            appendix_only=True,
        ),
        aggregate_key="cave_random_completion_scene_rate_consistency",
    ),
    FigureJob(
        spec=SortedGainGridSpec(
            figure_id="cave_completion_scene_gain_sorted_debug",
            family="sorted_gain_grid",
            title="(Appendix/Debug) Sorted scene gains across missing rates",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="cave_completion_scene_gain_sorted_debug",
                role="appendix_wide",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/appendix/cave_completion_scene_gain_sorted_debug.png",
            latex_width="\\textwidth",
            height=4.9,
            panels=(
                PanelSpec("rho_0.1", r"$\rho=0.1$", "Sorted scenes", r"$\Delta$RMSE*"),
                PanelSpec("rho_0.3", r"$\rho=0.3$", "Sorted scenes", r"$\Delta$RMSE*"),
                PanelSpec("rho_0.5", r"$\rho=0.5$", "Sorted scenes", r"$\Delta$RMSE*"),
                PanelSpec("rho_0.7", r"$\rho=0.7$", "Sorted scenes", r"$\Delta$RMSE*"),
            ),
            recommended_pairing="Appendix/debug only; replaced by scene-rate heatmaps in main text.",
            appendix_only=True,
        ),
        aggregate_key="cave_random_completion_scene_improvement",
    ),
    FigureJob(
        spec=CompletionVisualGridSpec(
            figure_id="cave_completion_visual_grid",
            family="completion_visual_grid",
            title="CAVE random-missing completion: missing-region visual evidence",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="cave_completion_visual_grid",
                role="double_column",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/main/cave_completion_visual_grid.png",
            latex_width="\\textwidth",
            height=3.25,
            panel_order=(
                "original",
                "observed_input",
                "tucker_completion",
                "ntdpl_completion",
                "tucker_missing_error",
                "ntdpl_missing_error",
                "missing_error_reduction",
            ),
            panel_titles=(
                "GT",
                "Observed",
                "Tucker",
                "NTD-PL",
                "Tucker err*",
                "NTD-PL err*",
                "Err. reduction",
            ),
            show_colorbars=False,
            recommended_pairing="Primary completion visual evidence figure in main text.",
        ),
        aggregate_key="cave_random_completion_visual_grid",
    ),
    FigureJob(
        spec=HeatmapPairSpec(
            figure_id="cave_completion_advantage_heatmap",
            family="heatmap_pair",
            title="CAVE completion advantage heatmap",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="cave_completion_advantage_heatmap",
                role="double_column",
            ),
            latex_path="./inputs/figures/main/cave_completion_advantage_heatmap.pdf",
            latex_width="\\textwidth",
            height=2.85,
            x_label="Diff. quartile",
            y_label="Bdry quartile",
            left_value_col="delta_rmse_missing",
            right_value_col="delta_sam_missing",
            left_title=r"$\Delta$RMSE*",
            right_title=r"$\Delta$SAM*",
            left_value_label=r"$\Delta$RMSE*",
            right_value_label=r"$\Delta$SAM*",
            cmap="RdBu_r",
            center_zero=True,
            x_col="difficulty_quartile",
            y_col="boundary_quartile",
            annotate_cells=True,
            show_colorbar=False,
            square_axes=True,
            square_cells=True,
            shared_color_scale=False,
            recommended_pairing="Standalone main-text figure.",
        ),
        aggregate_key="cave_random_completion_advantage_heatmap",
    ),
    FigureJob(
        spec=SpatialCaseGridSpec(
            figure_id="cave_completion_advantage_spatial_case",
            family="spatial_case_grid",
            title="Spatial localization of hard+boundary advantage",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="cave_completion_advantage_spatial_case",
                role="appendix_wide",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/appendix/cave_completion_advantage_spatial_case.pdf",
            latex_width="\\textwidth",
            height=3.0,
            panel_order=("original", "difficulty", "boundary", "gain"),
            panel_titles=(
                "Original / pseudo-RGB",
                "Tucker difficulty map (RMSE*)",
                "Boundary score map",
                "Missing-only error reduction",
            ),
            show_colorbars=False,
            show_notes=False,
            recommended_pairing="Appendix-facing spatial support for hard-pixel/boundary findings.",
            appendix_only=True,
        ),
        aggregate_key="cave_random_completion_advantage_spatial_case",
    ),
    FigureJob(
        spec=LineGridSpec(
            figure_id="mechanism_closure_main_figure",
            family="line_grid",
            title="Mechanism closure comparison",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="mechanism_closure_main_figure",
                role="double_column",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/main/mechanism_closure_main_figure.png",
            latex_width="\\textwidth",
            height=4.1,
            shared_legend=False,
            plot_kind="bar",
            emphasize_diff=True,
            panels=(
                PanelSpec("A", "(a) Recon RMSE", "", "RMSE", x_order=(1, 2, 3), x_tick_labels=("Tucker", "PolyCal", "NTD-PL")),
                PanelSpec("B", "(b) Recon SAM", "", "SAM", x_order=(1, 2, 3), x_tick_labels=("Tucker", "PolyCal", "NTD-PL")),
                PanelSpec("C", "(c) Completion RMSE*", "", "RMSE*", x_order=(1, 2, 3), x_tick_labels=("Tucker", "PolyCal", "NTD-PL")),
                PanelSpec("D", "(d) Completion SAM*", "", "SAM*", x_order=(1, 2, 3), x_tick_labels=("Tucker", "PolyCal", "NTD-PL")),
            ),
            method_order=("Tucker", "Tucker + PolyCal", "NTD-PL"),
            recommended_pairing="Primary mechanism figure supporting low-to-mid order saturation.",
        ),
        aggregate_key="mechanism_closure_main_figure",
    ),
    FigureJob(
        spec=LinePlusHeatmapSpec(
            figure_id="cave_parameter_mechanism",
            family="line_plus_heatmap",
            title="CAVE parameter mechanism",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="cave_parameter_mechanism",
                role="double_column",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/main/cave_parameter_mechanism.pdf",
            latex_width="\\textwidth",
            height=3.8,
            left_panel=PanelSpec(
                "left",
                "(a) Performance vs degree",
                r"Degree $P$",
                "RMSE*",
            ),
            right_panel=PanelSpec(
                "right",
                "(b) Effective contribution",
                "Term degree",
                r"Degree $P$",
            ),
            cmap="YlGnBu",
            value_label="Contribution ratio",
            show_colorbar=False,
            recommended_pairing="Main mechanism figure for low-to-mid order sufficiency.",
        ),
        aggregate_key="cave_parameter_mechanism_main_figure",
    ),
    FigureJob(
        spec=LineGridSpec(
            figure_id="gain_cr_curves",
            family="line_grid",
            title="Gain versus compression ratio",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="gain_cr_curves",
                role="double_column",
            ),
            latex_path="./inputs/figures/main/gain_cr_curves.pdf",
            latex_width="\\textwidth",
            height=2.9,
            shared_legend=False,
            panels=(
                PanelSpec("CAVE", "CAVE", "Compression ratio", "RMSE gain (%)"),
                PanelSpec("External HSI", "External HSI", "Compression ratio", "RMSE gain (%)"),
            ),
            method_order=("series",),
            recommended_pairing="Main-text gain-CR sweep for CAVE and external HSI.",
        ),
        aggregate_key="gain_cr_curves",
    ),
    FigureJob(
        spec=LineGridSpec(
            figure_id="real_hsi_robustness_overview",
            family="line_grid",
            title="Cross-dataset robustness overview on real HSI",
            subtitle=None,
            export=ExportTarget(
                section="main",
                stem="real_hsi_robustness_overview",
                role="double_column",
                formats=("pdf", "png"),
            ),
            latex_path="./inputs/figures/main/real_hsi_robustness_overview.pdf",
            latex_width="\\textwidth",
            height=3.4,
            shared_legend=True,
            panels=(
                PanelSpec(
                    "reconstruction",
                    "Reconstruction",
                    "",
                    "RMSE",
                    x_order=(1.0, 2.0, 3.0, 4.0),
                    x_tick_labels=("Jasper Ridge", "Samson", "Urban", "Cuprite"),
                ),
                PanelSpec(
                    "completion",
                    "Completion",
                    "",
                    "RMSE*",
                    x_order=(1.0, 2.0, 3.0, 4.0),
                    x_tick_labels=("Jasper Ridge", "Samson", "Urban", "Cuprite"),
                ),
            ),
            method_order=("Tucker", "NTD-PL"),
            recommended_pairing="Main-text overview: same-direction gains across most datasets with varying magnitudes.",
        ),
        aggregate_key="real_hsi_robustness_overview",
    ),
    FigureJob(
        spec=GeometryEvolutionSpec(
            figure_id="geometry_link_evolution",
            family="geometry_evolution",
            title="From linear link to progressively stronger nonlinear generation",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="geometry_link_evolution",
                role="appendix_wide",
            ),
            latex_path="./inputs/figures/appendix/geometry_link_evolution.pdf",
            latex_width="\\textwidth",
            height=5.15,
            alpha=0.3,
            order_values=(1, 2, 3, 4),
            appendix_only=True,
            note="Primary static explanation of progressive nonlinear activation.",
        ),
        aggregate_key="geometry_link_evolution",
    ),
    FigureJob(
        spec=GeometryResponseMapsSpec(
            figure_id="geometry_response_maps",
            family="geometry_response_maps",
            title="Local response maps induced by progressively activated link orders",
            subtitle=None,
            export=ExportTarget(
                section="appendix",
                stem="geometry_response_maps",
                role="appendix_wide",
            ),
            latex_path="./inputs/figures/appendix/geometry_response_maps.pdf",
            latex_width="\\textwidth",
            height=3.9,
            alpha=0.3,
            order_values=(1, 2, 3, 4),
            appendix_only=True,
            note="Appendix-only response-map view that replaces the old 3D surface figure.",
        ),
        aggregate_key="geometry_response_maps",
    ),
]


_FIGURE_JOB_MAP = {job.figure_id: job for job in FIGURE_REGISTRY}


def get_figure_job(figure_id: str) -> FigureJob:
    return _FIGURE_JOB_MAP[figure_id]
